In [ ]:
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow import keras
import numpy as np
(xtrain,ytrain),(xtest,ytest)=tf.keras.datasets.fashion_mnist.load_data()

4431872/4422102 [==============================] - 0s 0us/step


In [ ]:
xtrain.shape

(60000, 28, 28)

In [ ]:
xtrain=xtrain/255
xtest=xtest/255

In [ ]:
ytrain[0]

9

In [ ]:
ytrain[:-1]

array([9, 0, 0, ..., 1, 3, 0], dtype=uint8)

In [ ]:
# cnn
xtrain.shape

(60000, 28, 28)

In [ ]:
ytrain

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

In [ ]:
cnn = keras.models.Sequential([
    keras.layers.Conv2D(filters=28, kernel_size=(3, 3), activation='relu', input_shape=(28,28,1),),
    keras.layers.MaxPooling2D((2, 2)),
    keras.layers.Conv2D(filters=56, kernel_size=(3, 3), activation='relu'),
    keras.layers.MaxPooling2D((2, 2)),
    keras.layers.Flatten(),
    keras.layers.Dense(56, activation='relu'),
    keras.layers.Dense(10, activation='softmax')
])
cnn.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
cnn.fit(xtrain, ytrain, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 52s 27ms/step - loss: 0.4812 - accuracy: 0.8270
Epoch 2/10
1875/1875 [==============================] - 51s 27ms/step - loss: 0.3302 - accuracy: 0.8810
Epoch 3/10
1875/1875 [==============================] - 51s 27ms/step - loss: 0.2838 - accuracy: 0.8970
Epoch 4/10
1875/1875 [==============================] - 50s 27ms/step - loss: 0.2524 - accuracy: 0.9078
Epoch 5/10
1875/1875 [==============================] - 51s 27ms/step - loss: 0.2300 - accuracy: 0.9150
Epoch 6/10
1875/1875 [==============================] - 50s 27ms/step - loss: 0.2091 - accuracy: 0.9227
Epoch 7/10
1875/1875 [==============================] - 50s 27ms/step - loss: 0.1922 - accuracy: 0.9282
Epoch 8/10
1875/1875 [==============================] - 50s 27ms/step - loss: 0.1772 - accuracy: 0.9335
Epoch 9/10
1875/1875 [==============================] - 51s 27ms/step - loss: 0.1616 - accuracy: 0.9384
Epoch 10/10
1875/1875 [==============================] - 51s 27m

In [ ]:
cnn.evaluate(xtest,ytest)

313/313 [==============================] - 3s 9ms/step - loss: 0.2732 - accuracy: 0.9072


[0.2732444405555725, 0.9071999788284302]

In [ ]:
ypred=cnn.predict(xtest)
ypred

array([[6.99746872e-10, 1.82591761e-10, 4.46884757e-14, ...,
        6.91792229e-05, 5.46657475e-09, 9.99878645e-01],
       [9.36875585e-06, 1.58235125e-16, 9.93968606e-01, ...,
        2.28464681e-13, 1.18568775e-11, 4.64646099e-09],
       [1.83825403e-11, 1.00000000e+00, 4.64250527e-10, ...,
        1.89630467e-24, 1.19574368e-11, 3.41235950e-18],
       ...,
       [3.63776920e-08, 8.72188155e-11, 1.47882657e-08, ...,
        3.07505271e-11, 9.99998569e-01, 6.52885038e-11],
       [3.04642001e-09, 1.00000000e+00, 3.95920768e-10, ...,
        5.91339219e-19, 1.44944987e-10, 1.03198063e-13],
       [1.47042010e-05, 7.86090311e-07, 3.41387677e-05, ...,
        1.46385565e-01, 1.54456168e-01, 1.40783814e-04]], dtype=float32)

In [ ]:
np.argmax(ypred[0])

9

In [ ]:
ytest[0]

9

In [ ]:
y=[]
for i in ypred:
  y.append(np.argmax(i))

In [ ]:
from sklearn.metrics import classification_report
print('Classification report: \n',classification_report(ytest,y))

Classification report: 
               precision    recall  f1-score   support

           0       0.87      0.81      0.84      1000
           1       0.99      0.97      0.98      1000
           2       0.88      0.84      0.86      1000
           3       0.90      0.92      0.91      1000
           4       0.87      0.85      0.86      1000
           5       0.98      0.98      0.98      1000
           6       0.69      0.79      0.74      1000
           7       0.95      0.98      0.96      1000
           8       0.98      0.98      0.98      1000
           9       0.98      0.96      0.97      1000

    accuracy                           0.91     10000
   macro avg       0.91      0.91      0.91     10000
weighted avg       0.91      0.91      0.91     10000

